FROM golang:1.18 AS builder

WORKDIR /app

COPY *.go ./

RUN go mod init desafio_go && \
    go build -o desafio_go

FROM scratch
WORKDIR /app
COPY --from=builder /app/desafio_go .
ENTRYPOINT ["/app/desafio_go"]
